/*
 Copyright 2013 Blue State Digital, Inc.
 Blue State Digital Google Analytics Integration Library

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var _gaq=_gaq||[],optimizely=optimizely||[];_gaq.push(["_setSiteSpeedSampleRate",10],["_setAllowAnchor",!0],["_setAllowLinker",!0]);
(function(c){function q(a){var b=document.createElement("a");b.href=a;return b}function r(a){return a.charAt(0).toUpperCase()+a.slice(1).toLowerCase()}function n(a){return a&&q(a).pathname.replace(/(^\/?)/,"/")}function f(a){return(RegExp("(?:^|; )"+a+"=([^;]*)").exec(document.cookie)||[]).pop()}function l(a,b,g){ga_integration_config.nocookie||(g=g?"; expires="+(new Date(864E5*g+(new Date).getTime())).toGMTString():"",document.cookie=a+"="+b+g+"; path=/; domain="+ga_integration_config.cookiedomain)}
function p(a,b,g,c,h){e.event(a,b,c,h);e.social(a,b,g,c)}function s(a){var b=1,c=0,d;if(a)for(b=0,d=a.length-1;0<=d;d--)c=a.charCodeAt(d),b=(b<<6&268435455)+c+(c<<14),c=b&266338304,b=0!=c?b^c>>21:b;return b}function t(a){return a.match(/contribution/i)&&c("form#contribution").length?(a=Math.round(c("#amt_other:checked").length?c('input[name="amount_other"]').val():c('input[name="amount"]:checked').val()),a!=a||1E9<Math.abs(a)?0:a):0}function u(a){ga_integration_config.data.action=a;var b=a.modulename;
if(b){l("_bsda_s",1,180);var g=a.formname,d=a.transaction_amt;if(a.savedPaymentInfo)b="Quick Donate Opt-In",l("_bsda_q",1,180);else if(d){l("_bsda_c",Math.round(d),180);var h=a.contribution_key,k=-1!==c.inArray(d,a.pageamounts)?Math.round(d):"other",k=a.contribution_page_id+"_"+k,v=+a.pagetype,f=+a.is_recurring?"BSD Recurring":"BSD";a.used_quick_donate&&(f+=" Quick Donate",k+="_QD",l("_bsda_q",1,180));e.ecommerce(h,d,k,g,f+(4===v?" Memberships":2===v?" Tickets":3===v?" Custom Contributions":" Contributions"));
optimizely.push(["trackEvent","bsdtracker",100*d])}e.event("Completions",b,g,Math.ceil(d||0));optimizely.push(["trackEvent","bsdtracker_"+b])}}window.ga_integration_config=window.ga_integration_config||{};var e={event:function(){var a=Array.prototype.slice.call(arguments,0);window._gaq&&_gaq.push(["_trackEvent"].concat(a));if("function"===typeof ga)try{a[5]&&!0===a[5]&&(a[5]={nonInteraction:1}),ga.apply(this,["send","event"].concat(a))}catch(b){}},social:function(){var a=Array.prototype.slice.call(arguments,
0);window._gaq&&_gaq.push(["_trackSocial"].concat(a));if("function"===typeof ga)try{ga.apply(this,["send","social"].concat(a))}catch(b){}},custom:function(){var a=Array.prototype.slice.call(arguments,0);window._gaq&&_gaq.push(["_setCustomVar"].concat(a).concat(2));if("function"===typeof ga)try{"false"!==a[2]&&ga.apply(this,["set","dimension"+a[0],a[1]+a[2]])}catch(b){}},ecommerce:function(a,b,c,d,h){window._gaq&&_gaq.push(["_addTrans",a,"",b,"0","0","","",""],["_addItem",a,c,d,h,b,"1"],["_trackTrans"]);
if("function"===typeof ga)try{ga("require","ecommerce","ecommerce.js"),ga("ecommerce:addTransaction",{id:a,affiliation:"",revenue:b,shipping:"0",tax:"0"}),ga("ecommerce:addItem",{id:a,name:d,sku:c,category:h,price:b,quantity:"1"}),ga("ecommerce:send")}catch(k){}},queue:function(a){window._gaq&&_gaq.push(a);if("function"===typeof ga)try{ga(a)}catch(b){}}};if(!ga_integration_config.cookiedomain){var w=location.hostname.match(/\.uk$/)?-3:-2;ga_integration_config.cookiedomain=location.hostname.split(".").slice(w).join(".")}var x=
window.onerror;window.onerror=function(a,b,c){x&&x.apply(this,arguments);e.event("JavaScript Errors",a,b+"_"+c,0,!0)};var m=function(){var a={};location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi,function(b,c,d){a[c]=d});return a}();m.source&&e.custom(1,"Source",m.source);m.subsource&&e.custom(5,"Subsource",m.subsource);f("msid")&&(w=ga_integration_config.msid_seed?""+(parseInt(f("msid"),16)^ga_integration_config.msid_seed):f("msid"),e.custom(2,"msid",w));e.custom(3,"Has GUID",""+!!f("guid"));e.custom(4,
"Has Spud",""+!!f("spud"));if(!c||!c.fn)throw Error("No jQuery found.");c.fn.analytics=function(a,b,g){if(!a)return this.trigger(b||"mousedown");var d=b?b+".analytics":"keydown.analytics mousedown.analytics",h=g||"one",k=function(d){if(b||"mousedown"===d.type||13===d.which)"function"===typeof a?a.apply(this):c.isArray(a)&&a[1]&&"number"!==typeof a[1]?e.event(a):("string"===typeof a||c.isArray(a))&&optimizely.push(["trackEvent"].concat(a))};return g&&!c.fn.live?c(document).delegate(this.selector,d,
k):this[h](d,k)};c.fn.registerBSDError=function(a){this.length&&e.event("Error",a,n(document.referrer),t(a),!0)};s(location.hostname)%7!==(new Date).getDay()||1!==Math.ceil(100*Math.random())||f("__bsdzh")||((new Image).src="//bsd-analytics.appspot.com/?"+c.param({hostname:location.hostname,src:c("script:last").attr("src"),jQ:c.fn.jquery}));ga_integration_config.util={createCookie:l,readCookie:f,getURLParam:m,hash:s,contrib_amt:t,bsdtracker_to_ga:u,getPathname:n,social_event:p,proper:r};ga_integration_config.data=
{};c(document).ready(function(){function a(b){if("mousedown"===b.type||13===b.which)$this=c(this),$this.unbind("keydown mousedown",a),b=$this.is("form")?$this:$this.closest("form"),b=b.attr("id")||b.attr("name")||b.attr("action")||"(none)",e.event("Form Submits",b,location.pathname,t(b))}c("input").filter('[type="image"],[type="submit"]').bind("mousedown",a);c("form").bind("keydown",a);c("span.signuperror").registerBSDError("Signup");c("div.contriberrorbanner").registerBSDError("Contribution");c("#invitationpage .error").registerBSDError("Share");
c("[href^='http'], [href^='//']").analytics(function(b){if(this.hostname!==location.hostname)if(b=/(facebook|twitter|addthis|youtube|pinterest)(\.com)/i.exec(this.href)){var a=this.href.match(/facebook\.com\/sharer.php/)?decodeURIComponent(this.href.replace("http://www.facebook.com/sharer.php?u=","")):this.href;p(r(b[1]),"click",a,n(a))}else e.event("Exits",q(this.href).hostname,this.href)},null,"live");c('a[href$=".pdf"]').analytics(function(b){e.event("PDF Clicks",c(this).text(),this.href,0,!0)});
c("video,audio").bind("play ended pause",function(b){e.event(r(this.nodeName),r(b.type),this.src,0,!0)});c.fn._link=c.fn._link||function(b,a){var d=a||location.hostname.split(".").slice(-2).join(".");this.one("click",function(a){~c.inArray(d,b)&&d!=this.hostname.split(".").slice(-2).join(".")&&($this=c(this),ga.queue(function(){$this.attr("href",function(b,a){return _gat._getTrackerByName()._getLinkerUrl(a,!0)})}))})};window.BSDTracker?u(BSDTracker[BSDTracker.signup?"signup":BSDTracker.contribution?
"contribution":""].jsonData):m.td&&c.getJSON((ga_integration_config.bsddomain?ga_integration_config.bsddomain:"//www.bluestatedigital.com")+"/page/tracking/action-decode?td="+m.td+"&callback=?",function(b){u(b)});window.bQuery&&bQuery.fn.mailcheck&&c("#email").blur(function(){var b=c(".bsd-mailcheck");if(b.length){var a=b.text();e.event("Mailcheck","Shown",a,0,!0);b=function(){e.event("Mailcheck","Clicked",a,0,!0)};c.fn.live?c(".bsd-mailcheck a").live("click",b):c("#signup").delegate(".bsd-mailcheck a",
"click",b)}});c(window).load(function(){optimizely.variationNamesMap&&c.each(optimizely.variationNamesMap,function(b,a){e.event("Optimizely",optimizely.allExperiments[b].name,a,0,!0)});!1!==ga_integration_config.nocookie&&!1!==ga_integration_config.nospud&&!1!==ga_integration_config.noloe&&f("guid")&&!f("loega")&&(ga_integration_config.bsddomain||location.pathname.match(/^\/page\//))&&c.getJSON((ga_integration_config.bsddomain||"")+"/page/graph/loe/"+f("guid")+"?callback=?",function(a){var c=[],d=
"",h=0;ga_integration_config.data.loe=a;for(var k in a)a[k]&&"boolean"===typeof a[k]&&c.push(k);c=c.length?c.sort().join("-"):"Anonymous";a.donor&&(h=Math.ceil(a.highest_previous_contribution),d=""+h,l("_bsda_c",h,180));a.email&&l("_bsda_s",1,180);a.qd_enrolled&&l("_bsda_q",1,180);e.event("Ladder of Engagement",c,d,h,!0);l("loega",1)});(function(){if(!0!==ga_integration_config.nospud&&!0!==ga_integration_config.nocookie){var a=f("__utmz")||"";if(!f("spud")&&!m.source&&!f("source")||a&&s(a).toString()!==
f("__bsdzh")){var e=(ga_integration_config.bsddomain?ga_integration_config.bsddomain:"")+"/page/spud?jsonp=?",d=function(){var d,e;e=a.split(".").slice(4).join(".").split("|");var f={};c.each(e,function(a,b){var c=b.split("=");c[1]&&!c[1].match(/^\(.*\)$/)&&(f[c[0]]=decodeURIComponent(c[1]))});if(f.utmgclid)d="cpc_google",e=f.utmctr;else{var g=[];c.each(f,function(a,b){"utmcmd"!==a&&"utmcsr"!==a&&g.push(b)});f.utmcmd&&f.utmcsr&&(d=f.utmcmd+"_"+f.utmcsr);e=g.sort().join("_")}d&&l("source",d,180);e&&
l("subsource",e,180)};l("__bsdzh",s(a));f("spud")?c.ajax({url:e,dataType:"jsonp",data:{type:"getm",field:"source,subsource"},jsonp:"jsonp",success:function(a){a.source||a.subsource||d()}}):d()}}})();window.FB&&FB.Event&&(FB.Event.subscribe("edge.create",function(a){p("Facebook","Like",a,n(a),1)}),FB.Event.subscribe("edge.remove",function(a){p("Facebook","Unlike",a,n(a),-1)}),FB.Event.subscribe("comment.create",function(a){p("Facebook","Comment",a.href,n(a.href),1)}),FB.Event.subscribe("comment.remove",
function(a){p("Facebook","Uncomment",a.href,n(a.href),-1)}));window.twttr&&twttr.events&&twttr.ready&&twttr.ready(function(a){"click tweet retweet follow favorite".replace(/\w+/g,function(e){a.events.bind(e,function(a){var b;a&&a.target&&(a.target.src?b=q(decodeURIComponent((a.target.src.match(/[&#?](url=)([^&]*)/)||[""]).pop())):a&&a.target&&a.target.href&&c.each(decodeURIComponent(a.target.search).replace(/\+/g," ").split(/&| |\=/g),function(a,c){if(c.match(/(^https?:\/\/)|(^www.)/))return b=q(c),
!1}));b&&p("Twitter",a.type,b.href.replace(b.hash,""),b.pathname)})})})})})})(window.jQuery||window.bQuery);